[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "news_collector"
version = "0.1.0"
description = "NewsAPI collector"
requires-python = ">=3.9"

[tool.setuptools]
packages = ["news_collector"]
