name: Collect news to Firestore

on:
  schedule:
    # GitHub Actions cron은 UTC 기준. 매 3시간마다 실행 예시
    - cron: "0 */3 * * *"
  workflow_dispatch: {}   # 수동 실행 버튼

jobs:
  collect:
    runs-on: ubuntu-latest
    env:
      NEWSAPI_KEY: ${{ secrets.NEWSAPI_KEY }}
      FIREBASE_SA_JSON: ${{ secrets.FIREBASE_SA_JSON }}
      GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/sa.json
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Write service account file
        run: |
          echo "$FIREBASE_SA_JSON" > "$GOOGLE_APPLICATION_CREDENTIALS"

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          elif [ -f pyproject.toml ]; then
            pip install .
          else
            pip install requests tqdm python-dateutil firebase-admin
          fi

      # (선택) 테스트도 돌리고 싶다면 활성화
      # - name: Run unit tests
      #   run: |
      #     pip install pytest responses
      #     pytest -q

      - name: Run collector (Firestore)
        run: |
          python -m news_collector.cli \
            --store firestore \
            --domains-file kr_domains.json \
            --languages ko,en \
            --since-hours 168 \
            --max-pages 1 \
            --limit 50
